fingerprint_node_version: 0.0.1


fingerprint_template_for_test: "Z9iwpOAYf+K1sQQyLHN+4Hdfvqvrs9SJ3lrvWUcYFYsctFXAgBJxZgWBNIKcw85Qx+8OG1sDZC177hzBeD8zw8CQNn0pIhwvrdhvssJkKdh71mY845J9bg6J7QEoj9MHHr2N0j2qw+ED1XS4qI+BcJGWJlhm3mU+jlsPuKb59Gr91TQhYTleA1TQZdPNkp8Blr5fSgpSNWg/uw64pvn0av3VNCFhOV4DVNBl082SnwGWvl9KClI1aD+7Drim+fRq/dU0IWE5XgNU0GXTzZKfAZa+X0oKUjVoP7sOuKb59Gr91TQhYTleA1TQZdPNkp8Blr5fSgpSNWg/uw64pvn0pg=="
